#!/bin/bash

# Simple Script to quickly download and install asciiaquarium
# for more information, see https://www.tecmint.com/20-funny-commands-of-liinux-ro-linux-is-fun-in-terminal/


# Check to ensure Perl libraries are installed
apt-get install libcurses-perl

# Switch to /tmp, download, and unpack animation code
cd /tmp
wget http://search.cpan.org/CPAN/authors/id/K/KB/KBAUCOM/Term-Animation-2.4.tar.gz
tar -zxvf Term-Animation-2.4.tar.gz

# Switch to unpack dir, and 'make' animation
cd Term-Animation-2.4/
perl Makefile.PL && make && make test
make install

# Switch to /tmp and download ASCIIquarium
cd /tmp
wget http://www.robobunny.com/projects/asciiquarium/asciiquarium.tar.gz --no-check-certificate

# Unpack and set up asciiquarium
tar -zxvf asciiquarium.tar.gz
cd asciiquarium_1.1/
cp asciiquarium /usr/local/bin
chmod 0755 /usr/local/bin/asciiquarium

# Instructions

echo ''
echo 'To see your fishies, type "asciiquarium" into the terminal' 


